### ISSUE TITLE
Stop after variable moved from iterator non-zero stepsize

### ISSUE THREAD

**Issue by Doomsel** [coldphysics/experiment-control#1]
**Describe the bug**
The experiment control stops (does not crash but does not begin a new cycle) after an iterator with a finite step size is moved to the static variables.

**To Reproduce**
1. Enter a non zero stepsize to an iterator variable in the GUI
2. Move the iterator to static
3. Control stops iterating

**Expected behavior**
Software continues iterating

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Control Version : 1.3.0.25
 - Hardware Type: NI

**Comment by ghareeb-falazi** [comment]
Resolved by pull request #7 
Will be included in the next release of the software
