### ISSUE TITLE
All windows open when changing sequence

### ISSUE THREAD

**Issue by tdiet** [coldphysics/experiment-control#20]
**Describe the bug**
Whenever you want to change the sequence or press "start" all analog and digital card windows open at once which is not only annoying but also slow.

**Expected behavior**
The only windows that should open when switching between different sequences are the Error window, variable comparison and the variables window.

Desktop (please complete the following information):

OS: Windows 10
Software Control Version: 1.4.0.
Hardware Type: NI

**Comment by ghareeb-falazi** [comment]
From the main window of the program click on `View/Options`. Then click on the `Display` dropdown item. There, you have an option to enable/disable showing Card Windows when loading a model or starting the output.
Please re-open the issue if this approach does not work for you.
