### ISSUE TITLE
Export visualization

### ISSUE THREAD

**Issue by Denstorefisk** [coldphysics/experiment-control#21]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to plot my sequence or bits of it, for instance for paper figures or theses, or just for documentation of experiments.

**Describe the solution you'd like**
Therefore, I would like an export button to get the data from the output visualization.

The export option should open a save-window that prompts you to chose a destination. The data can just be whatever the experimental control has already calculated, and in some simple file format.

If the user has to stop the experiment from cycling to use the export function, this is perfectly fine. 

I suggest putting the buttons here:

![export button feature request](https://user-images.githubusercontent.com/63640986/87059881-21c15000-c20a-11ea-8748-cf620e84bd9f.PNG)

![export button feature request 2](https://user-images.githubusercontent.com/63640986/87059884-2259e680-c20a-11ea-9fc2-320fc670187d.PNG)

**Comment by ghareeb-falazi** [comment]
@Denstorefisk Please check pull request #27  . Is this what you have in mind?

**Comment by Denstorefisk** [comment]
I ❤ the export option! It is even nicer than I had imagined! (sorry for late reply)

Sorry I reopened this, I was not very smart :)
