### ISSUE TITLE
Load advanced mode python scripts from file

### ISSUE THREAD

**Issue by Doomsel** [coldphysics/experiment-control#22]
**Is your feature request related to a problem? Please describe.**
The built-in editor for the advanced mode python scripts is tedious to use especially if the code gets longer since it has no search function and tab/space indentation is not distinguishable.

**Describe the solution you'd like**
Add the possibility to load the scripts from a file like the regular python script which are defined in the profile settings.

**Describe alternatives you've considered**
None

**Additional context**
-

**Comment by ghareeb-falazi** [comment]
solved by #25
