### ISSUE TITLE
Linear ramp with deactived tab inbetween

### ISSUE THREAD

**Issue by tripiti** [coldphysics/experiment-control#4]
**Describe the bug**
Following settings: Three tabs, the middle one is deactived. In the first tab the analog channel ends with a constant value. The third tab starts with a linear ramp. The end value of this ramp is the same as the constant value in the first tab, which means the linear ramp should do nothing. If someone modifies the deactived tab and changes the value of the channel, deactivates it again, the output behaves differently (in our case we saw a dramatic atom loss).

**To Reproduce**
see the "describe the bug"

**Expected behavior**
A deactivated tab should not influence the output at all

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Control Version 1.3.0.25 (svn 757-08.11.2019)
 - Hardware Type  AdWin

**Comment by ghareeb-falazi** [comment]
Fixed by #9 . Will be included in the next release
