### ISSUE TITLE
Missing global counters

### ISSUE THREAD

**Issue by Denstorefisk** [coldphysics/experiment-control#44]
**Describe the bug**
The software occasionally skips a GlobalCounter when running in 'always iterate' mode. The missing global counts seems to be correlated to quick changes to variables.

**To Reproduce**
1. Start experiment control, load your sequence or model
2. Click increase iterator and then click always increase. Stop increase iterator. 
3. Select a random static variable and make a change to it. Repeat this step a few times, the timing seems important.
4. Check database entries for the global counters

This reproduction scheme will not always reproduce the error. It seems to depend on the timing with respect to the cycle time frame. We are cycling fast, on the order of 1-2 seconds, maybe it is not easily reproducible with a lower repetition rate.

**Expected behavior**
We do not expect the experiment control to occasionally lose a global counter.

It is not causing a problem, but it is confusing.

**Screenshots**
![V_1 4 4 0_losing global counters](https://user-images.githubusercontent.com/63640986/110962718-8d3b5e80-8351-11eb-8fa7-58906307818d.PNG)

In this screenshot I change f1ch1tk1_uptime from 90 to 10, to 0, and then back to 90. Each change comes with a missing global counter. 

**Desktop (please complete the following information):**
 - Windows 10
 - Software Control Version 1.4.4
 - AdWin based system

**Additional context**
- We are currently saving on the order of 200 variable values to the database.
- Our cycle time is on the order of 1-2 seconds

**Comment by Denstorefisk** [comment]
I just realized that this bug is probably the same as the one already reported [here](https://github.com/coldphysics/experiment-control/issues/2)

**Comment by ghareeb-falazi** [comment]
Nasty "race-condition" bugs! I will try to look into it this weekend ...

**Comment by Denstorefisk** [comment]
Thanks for looking into this :)

**Comment by ghareeb-falazi** [comment]
This issue occurs even without the existence of iterators:

- Start from an empty model
- Create some non-0-duration-step
- Create one static variable
- Activate the `increase iterators` option 
- Activate the `always increase` option
- Deactivate the `increase iterators` option (this miraculously keeps the `always increase` option active internally)
- Start the experiment
- Change the value of the static variable a couple of times quickly (before the cycle is over)
- Notice how the global variable increases with a step value of 2 (always 2 even if more than 2 changes were done to the variable during a single cycle) !

This suggests two problems:

1. The option to always increase is not related to whether one is in iteration mode or not --> it must be taken out of there
2. There is a problem with how the `always increase` option works (increases 1 even if the model is changed, which also increases 1)
