### ISSUE TITLE
Less clicking to move entries in analog and digital boxes and variable view

### ISSUE THREAD

**Issue by Denstorefisk** [coldphysics/experiment-control#5]
**Why do I want this feature**
In order to move an entry to an earlier or later time in the analog and digital boxes in the experimen gui you need to right click and pick 'Move left'/'move right'. The same is true in the variable view dynamic section (though it is not back or forth in time, but up and down in code).

Often it is necessary to move multiple entries in the variable view quire far, and this clicking becomes a pain.

**A possible solution**
Therefore, I would love to be able to click inside the entry window of the box of interest and move it by pressing 'l' and 'r' in the digital and analog boxes and 'u' and 'd' in the variable view.

The buttons are of course arbitrary. Could be wasd or arrows. Could also be click and drag, but this I guess is more computation heavy than just making a 'short cut' for a right click.
![move_boxes_digitalBoxes](https://user-images.githubusercontent.com/63640986/79211626-c2d87e80-7e46-11ea-9da3-9a18627cb77a.png)

![move_boxes_analogBoxes](https://user-images.githubusercontent.com/63640986/79212095-64f86680-7e47-11ea-9001-d3570ba331a8.png)

![move_boxes_variablesView](https://user-images.githubusercontent.com/63640986/79211084-041c5e80-7e46-11ea-8d72-8ce0fbe63867.png)

**Comment by ghareeb-falazi** [comment]
Implemented fully in PR #11 (go there to see instructions).
Will be included in the next release.
